/* Copyright reserved by KenLee@hellokenlee@163.com */

#ifndef D3D12_H
#define D3D12_H

#define CONCAT_IMPL(a, b) a##b
#define CONCAT(a, b) CONCAT_IMPL(a, b)

#define NENE_D3D_SHARED_SHADER_REGISTER_SPACE 0
#define NENE_D3D_VERTEX_SHADER_REGISTER_SPACE 1
#define NENE_D3D_HULL_SHADER_REGISTER_SPACE 2
#define NENE_D3D_DOMAIN_SHADER_REGISTER_SPACE 3
#define NENE_D3D_GEOMETRY_SHADER_REGISTER_SPACE 4
#define NENE_D3D_PIXEL_SHADER_REGISTER_SPACE 5

#define NENE_D3D_STATIC_SAMPLER_REGISTER_SPACE 100

#define SPACE CONCAT(space, NENE_D3D_SHARED_SHADER_REGISTER_SPACE)
#define SPACE_VS CONCAT(space, NENE_D3D_VERTEX_SHADER_REGISTER_SPACE)
#define SPACE_HS CONCAT(space, NENE_D3D_HULL_SHADER_REGISTER_SPACE)
#define SPACE_DS CONCAT(space, NENE_D3D_DOMAIN_SHADER_REGISTER_SPACE)
#define SPACE_GS CONCAT(space, NENE_D3D_GEOMETRY_SHADER_REGISTER_SPACE)
#define SPACE_PS CONCAT(space, NENE_D3D_PIXEL_SHADER_REGISTER_SPACE)
#define SPACE_STATIC_SAMPLER CONCAT(space, NENE_D3D_STATIC_SAMPLER_REGISTER_SPACE)


#define NENE_STATIC_SAMPLER_SLOT_POINT_WRAP 0 
#define NENE_STATIC_SAMPLER_SLOT_POINT_CLAMP 1
#define NENE_STATIC_SAMPLER_SLOT_LINEAR_WRAP 2
#define NENE_STATIC_SAMPLER_SLOT_LINEAR_CLAMP 3

#define SLOT_POINT_WRAP CONCAT(s, NENE_STATIC_SAMPLER_SLOT_POINT_WRAP)
#define SLOT_POINT_CLAMP CONCAT(s, NENE_STATIC_SAMPLER_SLOT_POINT_CLAMP)
#define SLOT_LINEAR_WRAP CONCAT(s, NENE_STATIC_SAMPLER_SLOT_LINEAR_WRAP)
#define SLOT_LINEAR_CLAMP CONCAT(s, NENE_STATIC_SAMPLER_SLOT_LINEAR_CLAMP)


#endif // D3D12_H